#######################
### digital-replica ###
#######################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-twin-app-deployment
  labels:
    app: digital-twin-service
    node: digital-twin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      node: digital-twin-app
  template:
    metadata:
      labels:
        node: digital-twin-app
    spec:
      containers:
      - name: digital-twin-app
        image: adamzr2000/isaac-sim:2023.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: "http://roscore-edge:11311"
        - name: ROS_HOSTNAME
          value: "digital-twin-app"
        - name: ACCEPT_EULA
          value: "Y"
        - name: PRIVACY_CONSENT
          value: "Y"
        volumeMounts:
        - name: cache-kit
          mountPath: /isaac-sim/kit/cache
        - name: cache-ov
          mountPath: /root/.cache/ov
        - name: cache-pip
          mountPath: /root/.cache/pip
        - name: cache-glcache
          mountPath: /root/.cache/nvidia/GLCache
        - name: cache-computecache
          mountPath: /root/.nv/ComputeCache
        - name: logs
          mountPath: /root/.nvidia-omniverse/logs
        - name: data
          mountPath: /root/.local/share/ov/data
        - name: documents
          mountPath: /root/Documents
        - name: my-environments
          mountPath: /isaac-sim/my-environments
        ports:
        - containerPort: 47995
        - containerPort: 47996
        - containerPort: 47997
        - containerPort: 47998
        - containerPort: 47999
        - containerPort: 48000
        - containerPort: 48001
        - containerPort: 48002
        - containerPort: 48003
        - containerPort: 48004
        - containerPort: 48005
        - containerPort: 48006
        - containerPort: 48007
        - containerPort: 48008
        - containerPort: 48009
        - containerPort: 48010
        - containerPort: 48011
        - containerPort: 48012
        - containerPort: 49000
        - containerPort: 49001
        - containerPort: 49002
        - containerPort: 49003
        - containerPort: 49004
        - containerPort: 49005
        - containerPort: 49006
        - containerPort: 49007
        - containerPort: 49100
        - containerPort: 8211
        - containerPort: 8011
        - containerPort: 8111
        - containerPort: 8311
        command: ["bash", "-c", "./runheadless.native.sh -v"]
        securityContext:
            privileged: true
      runtimeClassName: nvidia
      volumes:
      - name: cache-kit
        hostPath:
          path: /home/desire6g/docker/isaac-sim/cache/kit
      - name: cache-ov
        hostPath:
          path: /home/desire6g/docker/isaac-sim/cache/ov
      - name: cache-pip
        hostPath:
          path: /home/desire6g/docker/isaac-sim/cache/pip
      - name: cache-glcache
        hostPath:
          path: /home/desire6g/docker/isaac-sim/cache/glcache
      - name: cache-computecache
        hostPath:
          path: /home/desire6g/isaac-sim/cache/computecache
      - name: logs
        hostPath:
          path: /home/desire6g/docker/isaac-sim/logs
      - name: data
        hostPath:
          path: /home/desire6g/docker/isaac-sim/data
      - name: documents
        hostPath:
          path: /home/desire6g/docker/isaac-sim/documents
      - name: my-environments
        hostPath:
          path: /home/desire6g/unitree-go1-digital-twin/digital-twin-service/digital-replica/my-environments
      nodeSelector:
        nodetype: edge

---

### Headless service declaration.
### This is required to map to app "digital-twin-app" so that other pods can DNS its IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: digital-twin-app
  labels:
    app: digital-twin-service
    node: digital-twin-app
spec:
  clusterIP: None
  selector:
    node: digital-twin-app

---

### LoadBalancer service declaration.
### This is required to expose the ports that enable web access to the digital-twin-app container
apiVersion: v1
kind: Service
metadata:
  name: digital-twin-app-frontend
  labels:
    app: digital-twin-service
    node: digital-twin-app
spec:
  type: LoadBalancer
  ports:
  - name: port-47995
    protocol: TCP
    port: 47995
    targetPort: 47995
  - name: port-47996
    protocol: TCP
    port: 47996
    targetPort: 47996
  - name: port-47997
    protocol: TCP
    port: 47997
    targetPort: 47997
  - name: port-47998
    protocol: TCP
    port: 47998
    targetPort: 47998
  - name: port-47999
    protocol: TCP
    port: 47999
    targetPort: 47999
  - name: port-48000
    protocol: TCP
    port: 48000
    targetPort: 48000
  - name: port-48001
    protocol: TCP
    port: 48001
    targetPort: 48001
  - name: port-48002
    protocol: TCP
    port: 48002
    targetPort: 48002
  - name: port-48003
    protocol: TCP
    port: 48003
    targetPort: 48003
  - name: port-48004
    protocol: TCP
    port: 48004
    targetPort: 48004
  - name: port-48005
    protocol: TCP
    port: 48005
    targetPort: 48005
  - name: port-48006
    protocol: TCP
    port: 48006
    targetPort: 48006
  - name: port-48007
    protocol: TCP
    port: 48007
    targetPort: 48007
  - name: port-48008
    protocol: TCP
    port: 48008
    targetPort: 48008
  - name: port-48009
    protocol: TCP
    port: 48009
    targetPort: 48009
  - name: port-48010
    protocol: TCP
    port: 48010
    targetPort: 48010
  - name: port-48011
    protocol: TCP
    port: 48011
    targetPort: 48011
  - name: port-48012
    protocol: TCP
    port: 48012
    targetPort: 48012
  - name: port-49000
    protocol: TCP
    port: 49000
    targetPort: 49000
  - name: port-49001
    protocol: TCP
    port: 49001
    targetPort: 49001
  - name: port-49002
    protocol: TCP
    port: 49002
    targetPort: 49002
  - name: port-49003
    protocol: TCP
    port: 49003
    targetPort: 49003
  - name: port-49004
    protocol: TCP
    port: 49004
    targetPort: 49004
  - name: port-49005
    protocol: TCP
    port: 49005
    targetPort: 49005
  - name: port-49006
    protocol: TCP
    port: 49006
    targetPort: 49006
  - name: port-49007
    protocol: TCP
    port: 49007
    targetPort: 49007
  - name: port-49100
    protocol: TCP
    port: 49100
    targetPort: 49100
  - name: port-8211
    protocol: TCP
    port: 8211
    targetPort: 8211
  - name: port-8011
    protocol: TCP
    port: 8011
    targetPort: 8011
  - name: port-8111
    protocol: TCP
    port: 8111
    targetPort: 8111
  - name: port-8311
    protocol: TCP
    port: 8311
    targetPort: 8311
  - name: port-udp-47995
    protocol: UDP
    port: 47995
    targetPort: 47995
  - name: port-udp-47996
    protocol: UDP
    port: 47996
    targetPort: 47996
  - name: port-udp-47997
    protocol: UDP
    port: 47997
    targetPort: 47997
  - name: port-udp-47998
    protocol: UDP
    port: 47998
    targetPort: 47998
  - name: port-udp-47999
    protocol: UDP
    port: 47999
    targetPort: 47999
  - name: port-udp-48000
    protocol: UDP
    port: 48000
    targetPort: 48000
  - name: port-udp-48001
    protocol: UDP
    port: 48001
    targetPort: 48001
  - name: port-udp-48002
    protocol: UDP
    port: 48002
    targetPort: 48002
  - name: port-udp-48003
    protocol: UDP
    port: 48003
    targetPort: 48003
  - name: port-udp-48004
    protocol: UDP
    port: 48004
    targetPort: 48004
  - name: port-udp-48005
    protocol: UDP
    port: 48005
    targetPort: 48005
  - name: port-udp-48006
    protocol: UDP
    port: 48006
    targetPort: 48006
  - name: port-udp-48007
    protocol: UDP
    port: 48007
    targetPort: 48007
  - name: port-udp-48008
    protocol: UDP
    port: 48008
    targetPort: 48008
  - name: port-udp-48009
    protocol: UDP
    port: 48009
    targetPort: 48009
  - name: port-udp-48010
    protocol: UDP
    port: 48010
    targetPort: 48010
  - name: port-udp-48011
    protocol: UDP
    port: 48011
    targetPort: 48011
  - name: port-udp-48012
    protocol: UDP
    port: 48012
    targetPort: 48012
  - name: port-udp-49000
    protocol: UDP
    port: 49000
    targetPort: 49000
  - name: port-udp-49001
    protocol: UDP
    port: 49001
    targetPort: 49001
  - name: port-udp-49002
    protocol: UDP
    port: 49002
    targetPort: 49002
  - name: port-udp-49003
    protocol: UDP
    port: 49003
    targetPort: 49003
  - name: port-udp-49004
    protocol: UDP
    port: 49004
    targetPort: 49004
  - name: port-udp-49005
    protocol: UDP
    port: 49005
    targetPort: 49005
  - name: port-udp-49006
    protocol: UDP
    port: 49006
    targetPort: 49006
  - name: port-udp-49007
    protocol: UDP
    port: 49007
    targetPort: 49007
  - name: port-udp-49100
    protocol: UDP
    port: 49100
    targetPort: 49100
  - name: port-udp-8211
    protocol: UDP
    port: 8211
    targetPort: 8211
  - name: port-udp-8011
    protocol: UDP
    port: 8011
    targetPort: 8011
  - name: port-udp-8111
    protocol: UDP
    port: 8111
    targetPort: 8111
  - name: port-udp-8311
    protocol: UDP
    port: 8311
    targetPort: 8311

  selector:
    node: digital-twin-app
