apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ros-network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "vxlan200",
      "mode": "l2",
      "ipam": {
        "type": "static"
      }
    }

---