apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-net
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "vxlan200",
      "mode": "l2",
      "ipam": {
        "type": "static"
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "test-net", "ips": ["172.20.50.12/24"] }
    ]'
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "while true; do sleep 3600; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine4
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "test-net", "ips": ["172.20.50.13/24"] }
    ]'
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "while true; do sleep 3600; done"]
