apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-net
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "vxlan200",
      "mode": "l2",
      "ipam": {
        "type": "static"
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "test-net", "ips": ["172.20.50.10/24"] }
    ]'
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "test-net", "ips": ["172.20.50.11/24"] }
    ]'
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
