{
 "title": "DESIRE6G - DIGITAL TWIN DEMO",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "K8s Node",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"monitoring\",\r\n  tag:    \"node\",\r\n  predicate: (r) => r._measurement == \"infrastructure\"\r\n)\r\n"
    }
   },
   {
    "name": "pod",
    "label": "K8s Pod",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket:    \"monitoring\",\n  tag:       \"pod\",\n  predicate: (r) => r._measurement == \"applications\"\n)\n"
    }
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"monitoring\",\n  tag: \"interface\",\n  predicate: (r) => r._measurement == \"network_io\"\n)\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage by Node",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => \n       r._measurement == \"infrastructure\" and\n       r._field       == \"cpu_pct\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> map(fn: (r) => ({ r with combined_label: r.node }))\n  |> keep(columns: [\"combined_label\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "RAM Usage by Node",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"mem_pct\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> map(fn: (r) => ({ r with combined_label: r.node }))\n  |> keep(columns: [\"combined_label\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"cpu_cores\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: { _value: \"cpu_cores\" })\n"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"alloc_cpu_cores\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: { _value: \"alloc_cpu_cores\" })\n"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"mem_gb\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: { _value: \"mem_gb\" })\n"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"alloc_mem_gb\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: { _value: \"alloc_mem_gb\" })\n"
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => \r\n       r._measurement == \"applications\" and\r\n       r._field       == \"net_tx_bytes\" and\r\n       r.pod          =~ /${pod:regex}/\r\n     )\r\n  |> map(fn: (r) => ({ r with combined_label: r.pod }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"])\r\n  |> group(columns: [\"combined_label\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n  |> yield(name: \"pod_cpu_mcores\")\r\n"
    }
   ]
  },
  {
   "title": "RAM Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => \r\n       r._measurement == \"applications\" and\r\n       r._field       == \"mem_mb\" and\r\n       r.pod          =~ /${pod:regex}/\r\n     )\r\n  |> map(fn: (r) => ({ r with combined_label: r.pod }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"])\r\n  |> group(columns: [\"combined_label\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n  |> yield(name: \"pod_mem_mb\")\r\n"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => \r\n       r._measurement == \"applications\" and\r\n       r._field       == \"cpu_mcores\" and\r\n       r.pod          =~ /${pod:regex}/\r\n     )\r\n  |> map(fn: (r) => ({ r with combined_label: r.pod }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"])\r\n  |> group(columns: [\"combined_label\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n  |> yield(name: \"pod_cpu_mcores\")\r\n"
    }
   ]
  },
  {
   "title": "Net I/O Throughput by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) =>\r\n       r._measurement == \"applications\" and\r\n       (r._field == \"net_rx_bytes\" or r._field == \"net_tx_bytes\") and\r\n       contains(value: r.pod, set: ${pod:json})\r\n     )\r\n  |> group(columns: [\"pod\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n       _time:  r._time,\r\n       _value: r._value * 8.0,\r\n       _field: r.pod + \" \" + (if r._field == \"net_tx_bytes\" then \"TX\" else \"RX\")\r\n     }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> yield(name: \"pod_network_throughput_bps\")\r\n"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Ping RTT Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"ping\")\n  |> filter(fn: (r) => r._field == \"latency_ms\")\n  |> map(fn: (r) => ({\n      r with\n      combined_label: r.target + \" [\" + r.ip + \"]\"\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"])\n  |> group(columns: [\"combined_label\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> yield(name: \"ping_latency\")\n"
    }
   ]
  },
  {
   "title": "I/O Throughput by Interface",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) =>\r\n       r._measurement == \"network_io\" and\r\n       (r._field == \"rx_bytes\" or r._field == \"tx_bytes\") and\r\n       contains(value: r.interface, set: ${interface:json})\r\n     )\r\n  |> group(columns: [\"interface\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n       _time:  r._time,\r\n       _value: r._value * 8.0,\r\n       _field: r.interface + \" \" + (if r._field == \"tx_bytes\" then \"TX\" else \"RX\")\r\n     }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> yield(name: \"net_interface_throughput_bps\")\r\n"
    }
   ]
  },
  {
   "title": "Ping Packet Loss (%)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"ping\")\n  |> filter(fn: (r) => r._field == \"packet_loss_percent\")\n  |> map(fn: (r) => ({\n      r with\n      combined_label: r.target + \" [\" + r.ip + \"]\"\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"])\n  |> group(columns: [\"combined_label\"])\n"
    }
   ]
  },
  {
   "title": "Ping Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"ping\")\n  |> filter(fn: (r) =>\n    r._field == \"total_pings\" or\n    r._field == \"successful_pings\" or\n    r._field == \"failed_pings\"\n  )\n  |> last()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => {\n      total   = float(v: r.total_pings)\n      success = float(v: r.successful_pings)\n      failed  = float(v: r.failed_pings)\n\n      return {\n        IP_Address: r.ip,\n        Total:       int(v: total),\n        Success:     int(v: success),\n        Failed:      int(v: failed)\n      }\n  })\n  |> keep(columns: [\"IP_Address\", \"Total\", \"Success\", \"Failed\"])\n  |> yield(name: \"Ping Summary\")\n"
    }
   ]
  },
  {
   "title": "Video Streaming App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput Rx (Mbps)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n    r._measurement == \"video_metrics\" and\n    r._field == \"bandwidth_mbps\"\n  )\n  |> map(fn: (r) => ({ \n    r with stream_label: r.stream\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"stream_label\"])\n  |> group(columns: [\"stream_label\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> yield(name: \"video_bandwidth\")\n"
      }
     ]
    },
    {
     "title": "Frames per Second (FPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "fps" } },
     "targets": [
      {
       "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"video_metrics\" and\n    r._field == \"fps\"\n  )\n  |> map(fn: (r) => ({\n    r with stream_label: r.stream\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"stream_label\"])\n  |> group(columns: [\"stream_label\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> yield(name: \"video_fps\")\n"
      }
     ]
    }
   ]
  }
 ]
}