version: '3.8'

x-ros-config: &ros-config
  - ROS_MASTER_URI=http://roscore-edge:11311

services:

  go1-base:
    image: go1-base:latest
    container_name: go1-base
    hostname: go1-base
    ports:       
      - "8082:8082/tcp"
      - "8082:8082/udp"
      - "8090:8090/tcp"
      - "8090:8090/udp"
      - "1131:1131/tcp"
      - "1131:1131/udp"
      - "8007:8007/tcp"
      - "8007:8007/udp"
    environment:
      ROS_MASTER_URI: "http://roscore-edge:11311"
      TARGET_IP: "192.168.123.161"
    network_mode: digital-twin-service

  lidar:
    image: rplidar-lidar:latest 
    environment: *ros-config
    container_name: lidar
    hostname: lidar
    devices:
      - "/dev/rplidar:/dev/rplidar"
    network_mode: digital-twin-service




