{
 "title": "Digital Twin ROS Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"delay\")\n  |> filter(fn: (r) => r._field == \"average_delay_ms\")\n  |> group(columns: [\"topic\"])\n  |> keep(columns: [\"_value\", \"_time\", \"topic\"])"
    }
   ]
  },
  {
   "title": "Delay Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"delay\")\n  |> filter(fn: (r) => \n      r._field == \"average_delay_ms\" or\n      r._field == \"min_delay_ms\" or\n      r._field == \"max_delay_ms\" or\n      r._field == \"std:_dev_delay_ms\"\n  )\n  |> group(columns: [\"topic\", \"_field\"])\n  |> last()\n  |> group() // Regroup to reset group keys after last\n  |> map(fn: (r) => ({\n      r with \n      _field: \n        if r._field == \"average_delay_ms\" then \"avg\"\n        else if r._field == \"min_delay_ms\" then \"min\"\n        else if r._field == \"max_delay_ms\" then \"max\"\n        else if r._field == \"std:_dev_delay_ms\" then \"std_dev\"\n        else r._field\n  }))\n  |> pivot(rowKey: [\"topic\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"jitter\")\n  |> filter(fn: (r) => r._field == \"jitter_ms\")\n  |> group(columns: [\"topic\"])\n  |> keep(columns: [\"_value\", \"_time\", \"topic\"])"
    }
   ]
  },
  {
   "title": "Jitter Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"jitter\")\n  |> filter(fn: (r) => \n      r._field == \"jitter_ms\" \n  )\n  |> group(columns: [\"topic\", \"_field\"])\n  |> last()\n  |> group() // Regroup to reset group keys after last\n  |> map(fn: (r) => ({\n      r with \n      _field: \n        if r._field == \"jitter_ms\" then \"avg\"\n        else r._field\n  }))\n  |> pivot(rowKey: [\"topic\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"bandwidth\")\n  |> filter(fn: (r) => r._field == \"average_bandwidth_kilobytes_s\")\n  |> group(columns: [\"topic\"])\n  |> keep(columns: [\"_value\", \"_time\", \"topic\"])"
    }
   ]
  },
  {
   "title": "Message Size",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"bandwidth\")\n  |> filter(fn: (r) => \n      r._field == \"average_message_size_bytes\" or\n      r._field == \"min_message_size_bytes\" or\n      r._field == \"max_message_size_bytes\" or\n      r._field == \"average_message_size_bytes\"\n  )\n  |> group(columns: [\"topic\", \"_field\"])\n  |> last()\n  |> group() // Regroup to reset group keys after last\n  |> map(fn: (r) => ({\n      r with \n      _field: \n        if r._field == \"a\" then \"avg\"\n        else if r._field == \"average_message_size_bytes\" then \"avg\"\n        else if r._field == \"min_message_size_bytes\" then \"min\"\n        else if r._field == \"max_message_size_bytes\" then \"max\"\n        else r._field\n  }))\n  |> pivot(rowKey: [\"topic\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"bandwidth\")\n  |> filter(fn: (r) => r._field == \"average_bandwidth_kilobytes_s\")\n  |> group(columns: [\"topic\"])\n  |> keep(columns: [\"_value\", \"_time\", \"topic\"])"
    }
   ]
  }
 ]
}