###########################
### gesture-control-app ###
###########################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gesture-control-app-deployment
  labels:
    app: digital-twin-service
    node: gesture-control-app
spec:
  replicas: 1
  selector:
    matchLabels:
      node: gesture-control-app
  template:
    metadata:
      labels:
        node: gesture-control-app
    spec:
      containers:
      - name: gesture-control-app
        image: go1-gesture-control
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: "http://ros-master:11311"
        - name: ROS_HOSTNAME
          value: "gesture-control-app"
        - name: CAMERA_TYPE
          value: "webcam_ip"
        - name: WEB_SERVER
          value: "yes"
        - name: CONTROL_LOOP_RATE
          value: "100"
        - name: CMD_VEL
          value: "go1_controller/cmd_vel"
        - name: STAMPED
          value: "false"
        ports:
        - containerPort: 8888
        volumeMounts:
          - name: webcam
            mountPath: /dev/video0
        securityContext:
          privileged: true
      volumes:
        - name: webcam
          hostPath:
            path: /dev/video0
      nodeSelector:
        nodetype: edge

---

### Headless service declaration.
### This is required to map to app "gesture-control-app" so that other pods can DNS its IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: gesture-control-app
  labels:
    app: digital-twin-service
    node: gesture-control-app
spec:
  clusterIP: None
  selector:
    node: gesture-control-app

---

### LoadBalancer service declaration.
### This is required to expose the ports that enable web access to the gesture-control-app container
apiVersion: v1
kind: Service
metadata:
  name: gesture-control-app-frontend
  labels:
    app: digital-twin-service
    node: gesture-control-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    node: gesture-control-app

---
