###########################
### go1-gesture-control ###
###########################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go1-gesture-control-deployment
  labels:
    app: digital-twin-service
    node: go1-gesture-control
spec:
  replicas: 1
  selector:
    matchLabels:
      node: go1-gesture-control
  template:
    metadata:
      labels:
        node: go1-gesture-control
    spec:
      containers:
      - name: go1-gesture-control
        image: go1-gesture-control
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: "http://ros-master:11311"
        - name: ROS_HOSTNAME
          value: "go1-gesture-control"
        - name: CAMERA_TYPE
          value: "webcam_ip"
        - name: WEB_SERVER
          value: "yes"
        - name: CONTROL_LOOP_RATE
          value: "100"
        - name: CMD_VEL
          value: "go1_controller/cmd_vel"
        - name: STAMPED
          value: "false"
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: webcam
            mountPath: /dev/video0
        securityContext:
          privileged: true
      volumes:
        - name: webcam
          hostPath:
            path: /dev/video0
      nodeSelector:
        nodetype: edge

---

### Headless service declaration.
### This is required to map to app "go1-gesture-control" so that other pods can DNS its IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: go1-gesture-control
  labels:
    app: digital-twin-service
    node: go1-gesture-control
spec:
  clusterIP: None
  selector:
    node: go1-gesture-control

---

### LoadBalancer service declaration.
### This is required to expose the ports that enable web access to the go1-gesture-control container
apiVersion: v1
kind: Service
metadata:
  name: go1-gesture-control-frontend
  labels:
    app: digital-twin-service
    node: go1-gesture-control
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 5000
  selector:
    node: go1-gesture-control

---
