#####################
### lidar-drivers ###
#####################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidar-deployment
  labels:
    app: digital-twin-service
    node: lidar
spec:
  replicas: 1
  selector:
    matchLabels:
      node: lidar
  template:
    metadata:
      labels:
        node: lidar
    spec:
      containers:
      - name: lidar
        image: rplidar-lidar
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: "http://roscore-edge:11311"
        - name: ROS_HOSTNAME
          value: "lidar"
        - name: RF2O_LASER_ODOMETRY
          value: "false"
        - name: ODOM_TOPIC
          value: "/odom"                    
        volumeMounts:
          - name: rplidar
            mountPath: /dev/rplidar
        securityContext:
          privileged: true
      volumes:
        - name: rplidar
          hostPath:
            path: /dev/rplidar
      nodeSelector:
        nodetype: robot

---

### Headless service declaration.
### This is required to map to app "lidar" so that other pods can DNS its IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: lidar
  labels:
    app: digital-twin-service
    node: lidar
spec:
  clusterIP: None
  selector:
    node: lidar

---