### video-streamer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streamer-deployment
  labels:
    app: video-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streamer
  template:
    metadata:
      labels:
        app: video-streamer
    spec:
      containers:
      - name: video-streamer
        image: video-streamer
        imagePullPolicy: IfNotPresent
        env:
        - name: "WIDTH"
          value: "1280"
        - name: "HEIGHT"
          value: "720"
        - name: "RECEIVER_IP"
          value: "video-receiver-transcoder"
        - name: "RECEIVER_PORT"
          value: "5554"
        - name: "DEVICE"
          value: "/dev/video0"
        - name: "USE_H264"
          value: "false"
        - name: "FRAMERATE"
          value: "30"
        securityContext:
          privileged: true
      nodeSelector:
        nodetype: robot
