################
### vizanti ###
################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vizanti-deployment
  labels:
    app: digital-twin-service
    node: vizanti
spec:
  replicas: 1
  selector:
    matchLabels:
      node: vizanti
  template:
    metadata:
      labels:
        node: vizanti
    spec:
      containers:
      - name: vizanti
        image: vizanti
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: "http://ros-master:11311"
        - name: ROS_HOSTNAME
          value: "vizanti"
        - name: IP_ADDRESS_ROSBRIDGE
          value: "0.0.0.0"
        ports:
        - containerPort: 5000
        - containerPort: 5001
        securityContext:
            privileged: true
      nodeSelector:
        nodetype: edge

---

### Headless service declaration.
### This is required to map to app "vizanti" so that other pods can DNS its IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: vizanti
  labels:
    app: digital-twin-service
    node: vizanti
spec:
  clusterIP: None
  selector:
    node: vizanti

---

### LoadBalancer service declaration.
### This is required to expose the ports that enable web access to the vizanti container
apiVersion: v1
kind: Service
metadata:
  name: vizanti-frontend
  labels:
    app: digital-twin-service
    node: vizanti
spec:
  type: LoadBalancer
  ports:
  - name: port-5000
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: port-5001
    protocol: TCP
    port: 5001
    targetPort: 5001
  selector:
    node: vizanti

---
