apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-net
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "vxlan200",
      "mode": "l2",
      "ipam": {
        "type": "static"
      }
    }

---

##################
### alpine1 ###
##################

apiVersion: v1
kind: Pod
metadata:
  name: alpine1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "test-net", "ips": ["172.20.50.10/24"] }
    ]'  
  labels:
    app: alpine-service
    node: alpine1
spec:
  containers:
  - name: alpine1
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "while true; do sleep 3600; done"]
  nodeSelector:
    nodetype: edge

---

##################
### alpine2 ###
##################

apiVersion: v1
kind: Pod
metadata:
  name: alpine2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "test-net", "ips": ["172.20.50.11/24"] }
    ]'  
  labels:
    app: alpine-service
    node: alpine2
spec:
  containers:
  - name: alpine2
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "while true; do sleep 3600; done"]

  nodeSelector:
    nodetype: robot

---
