apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-net-macvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.5.99.88/16",
          "gateway": "10.5.0.1"
        }
      ],
      "routes": [
        {
          "dst": "0.0.0.0/0",
          "gw": "10.5.0.1"
        }
      ]
    }
  }'

---

apiVersion: v1
kind: Pod
metadata:
  name: multus-test
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "test-net-macvlan" }]'
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
