apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-net-ipvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ipvlan",
    "master": "vxlan200",
    "mode": "l2",
    "ipam": {
      "type": "static"
    }
  }'

---

apiVersion: v1
kind: Pod
metadata:
  name: multus-test
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "test-net-ipvlan", "ips": ["10.10.10.10/24"] }
    ]'
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN

