apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-net-macvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "vxlan200",
    "mode": "bridge",
    "ipam": {
      "type": "static"
    },
    "plugins": [
      {
        "type": "tuning",
        "capabilities": { "mac": true }
      }
    ]
  }'

---

apiVersion: v1
kind: Pod
metadata:
  name: multus-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ 
      "name": "test-net-macvlan", 
      "ips": ["10.10.10.10/24"],
      "mac": "00:50:56:AA:BB:CC"
    }]'
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN

---

apiVersion: v1
kind: Pod
metadata:
  name: multus-pod-2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ 
      "name": "test-net-macvlan", 
      "ips": ["10.10.10.11/24"],
      "mac": "00:50:57:AA:BB:CC"
    }]'
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
