{
 "title": "Digital Twin ROS Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ROS Topic Average Delay",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"delay\")\n  |> filter(fn: (r) => r._field == \"average_delay_ms\")\n  |> filter(fn: (r) => r.topic == \"/scan\" or r.topic == \"/joint_states\" or r.topic == \"/go1_controller/odom\")\n  |> map(fn: (r) => ({\n      r with\n      topic_name: if r.topic == \"/scan\" then \"Laser Scan\" else if r.topic == \"/joint_states\" then \"Joint States\" else if r.topic == \"/go1_controller/odom\" then \"Odometry\" else if r.topic == \"/go1_controller/cmd_vel\" then \"Control\" else r.topic\n    }))\n  |> group(columns: [\"topic_name\"])\n  |> keep(columns: [\"_value\", \"_time\", \"topic_name\"])\n"
    }
   ]
  },
  {
   "title": "ROS Topic Average Jitter",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"jitter\")\n  |> filter(fn: (r) => r._field == \"jitter_ms\")\n  |> group(columns: [\"topic\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"topic\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      topic_name: if r.topic == \"/scan\" then \"Laser Scan\" else if r.topic == \"/joint_states\" then \"Joint States\" else if r.topic == \"/go1_controller/odom\" then \"Odometry\" else if r.topic == \"/go1_controller/cmd_vel\" then \"Control\" else r.topic\n    }))\n  |> group(columns: [\"topic_name\"])\n  |> keep(columns: [\"_value\", \"_time\", \"topic_name\"])\n"
    }
   ]
  },
  {
   "title": "ROS Topic Average Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 14, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"bandwidth\")\n  |> filter(fn: (r) => r._field == \"average_bandwidth_kbps\")\n  |> group(columns: [\"topic\"])\n  |> map(fn: (r) => ({\n      r with\n      topic_name: if r.topic == \"/scan\" then \"Laser Scan\" else if r.topic == \"/joint_states\" then \"Joint States\" else if r.topic == \"/go1_controller/odom\" then \"Odometry\" else if r.topic == \"/go1_controller/cmd_vel\" then \"Control\" else r.topic\n    }))\n  |> group(columns: [\"topic_name\"])\n  |> keep(columns: [\"_value\", \"_time\", \"topic_name\"])\n"
    }
   ]
  },
  {
   "title": "ROS Topic Average Message Size",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ros-metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"bandwidth\")\n  |> filter(fn: (r) => r._field == \"average_message_size_bytes\")\n  |> group(columns: [\"topic\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"topic\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      topic_name: if r.topic == \"/scan\" then \"Laser Scan\" else if r.topic == \"/joint_states\" then \"Joint States\" else if r.topic == \"/go1_controller/odom\" then \"Odometry\" else if r.topic == \"/go1_controller/cmd_vel\" then \"Control\" else r.topic\n    }))\n  |> group(columns: [\"topic_name\"])\n  |> keep(columns: [\"_value\", \"_time\", \"topic_name\"])\n"
    }
   ]
  }
 ]
}