######################
### go1-navigation ###
######################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go1-navigation-deployment
  labels:
    app: digital-twin-service
    node: go1-navigation
spec:
  replicas: 1
  selector:
    matchLabels:
      node: go1-navigation
  template:
    metadata:
      labels:
        node: go1-navigation
    spec:
      containers:
      - name: go1-navigation
        image: go1-navigation
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: "http://10.11.7.4:11311"
        - name: ROS_IP
          value: "10.11.7.4"
      hostNetwork: true      
      nodeSelector:
        nodetype: edge
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

---
