uint8 mode  # 0. idle, default stand  1. force stand (controlled by dBodyHeight + ypr)
            # 2. target velocity walking (controlled by velocity + yawSpeed)
            # 3. target position walking (controlled by position + ypr[0])
            # 4. path mode walking (reserve for future release)
            # 5. position stand down. 
            # 6. position stand up 
            # 7. damping mode 
            # 8. recovery stand
            # 9. backflip
            # 10. jumpYaw
            # 11. straightHand
            # 12. dance1
            # 13. dance2
uint8 gait_type            
---
bool success
