######################
### go1-navigation ###
######################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go1-navigation-deployment
  labels:
    app: digital-twin-service
    node: go1-navigation
spec:
  replicas: 1
  selector:
    matchLabels:
      node: go1-navigation
  template:
    metadata:
      labels:
        node: go1-navigation
    spec:
      containers:
      - name: go1-navigation
        image: go1-navigation
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: "http://roscore-edge:11311"
        - name: ROS_HOSTNAME
          value: "go1-navigation"
      nodeSelector:
        nodetype: edge
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

---

### Headless service declaration.
### This is required to map to app "go1-navigation" so that other pods can DNS its IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: go1-navigation
  labels:
    app: digital-twin-service
    node: go1-navigation
spec:
  clusterIP: None
  selector:
    node: go1-navigation

---
