##################
### ros-master ###
##################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-master-deployment
  labels:
    app: digital-twin-service
    node: ros-master
spec:
  replicas: 1
  selector:
    matchLabels:
      node: ros-master
  template:
    metadata:
      labels:
        node: ros-master
    spec:
      containers:
      - name: ros-master
        tty: true
        image: ros-master
        imagePullPolicy: IfNotPresent
        # env:
        # - name: ENABLE_STATISTICS
        #   value: "false"
        # - name: ROS_MASTER_URI
        #   value: "http://ros-master:11311"
        # - name: ROS_HOSTNAME
        #   value: "ros-master"
        ports:
        - containerPort: 11311
          name: roscore-port
      nodeSelector:
        nodetype: edge
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

---

### Headless service declaration.
### This is required to map to app "ros-master" so that other pods can DNS its IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: ros-master
  labels:
    app: digital-twin-service
    node: ros-master
spec:
  clusterIP: None
  selector:
    node: ros-master

---