{
 "title": "DESIRE6G - DIGITAL TWIN DEMO",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "K8s Node",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"monitoring\",\r\n  tag:    \"node\",\r\n  predicate: (r) => r._measurement == \"infrastructure\"\r\n)\r\n"
    }
   },
   {
    "name": "pod",
    "label": "K8s Pod",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket:    \"monitoring\",\n  tag:       \"pod\",\n  predicate: (r) => r._measurement == \"applications\"\n)\n"
    }
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"monitoring\",\n  tag: \"interface\",\n  predicate: (r) => r._measurement == \"network_io\"\n)\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kubernetes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"applications\")\n  |> filter(fn: (r) => exists r.node and r.node != \"\")\n  |> keep(columns: [\"node\"])\n  |> group(columns: [])                 // single table\n  |> distinct(column: \"node\")\n  |> count()\n  |> rename(columns: {_value: \"node_count\"})\n"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"applications\")\n  |> keep(columns: [\"pod\"])          // ensure we keep the tag\n  |> group(columns: [])              // single table\n  |> distinct(column: \"pod\")         // outputs a column named _value\n  |> count()                         // counts rows in _value\n  |> rename(columns: {_value: \"pod_count\"})\n"
    }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => \n       r._measurement == \"infrastructure\" and\n       r._field       == \"cpu_pct\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> map(fn: (r) => ({ r with combined_label: r.node }))\n  |> keep(columns: [\"combined_label\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "RAM Usage by Node",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"mem_pct\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> map(fn: (r) => ({ r with combined_label: r.node }))\n  |> keep(columns: [\"combined_label\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "List of Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"applications\")\n  |> filter(fn: (r) => exists r.node and r.node != \"\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> keep(columns: [\"pod\",\"node\"])\n  |> group(columns: [\"node\"])\n  |> distinct(column: \"pod\")\n  |> count()\n  |> rename(columns: {_value: \"Running pods\"})\n  |> duplicate(column: \"node\", as: \"Name\")\n  |> keep(columns: [\"Name\", \"Running pods\"])\n  |> group(columns: [])         // single table\n  |> sort(columns: [\"Name\"])\n"
    }
   ]
  },
  {
   "title": "List of Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"applications\" and r._field == \"cpu_mcores\"\n  )\n  |> filter(fn: (r) => exists r.pod and exists r.node and r.node != \"\")\n  |> last()\n  |> keep(columns: [\"pod\", \"node\"])\n  |> group(columns: [])\n  |> sort(columns: [\"pod\", \"node\"])\n  |> rename(columns: {pod: \"Name\", node: \"Running node\"})\n"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"cpu_cores\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: { _value: \"cpu_cores\" })\n"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"alloc_cpu_cores\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: { _value: \"alloc_cpu_cores\" })\n"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"mem_gb\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: { _value: \"mem_gb\" })\n"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"infrastructure\" and\n       r._field       == \"alloc_mem_gb\" and\n       r.node         == \"${node}\"\n     )\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: { _value: \"alloc_mem_gb\" })\n"
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => \r\n       r._measurement == \"applications\" and\r\n       r._field       == \"cpu_mcores\" and\r\n       r.pod          =~ /${pod:regex}/\r\n     )\r\n  |> map(fn: (r) => ({ r with combined_label: r.pod }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"])\r\n  |> group(columns: [\"combined_label\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n  |> yield(name: \"pod_cpu_mcores\")\r\n"
    }
   ]
  },
  {
   "title": "Net I/O Throughput by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n       r._measurement == \"applications\" and\n       (r._field == \"net_rx_bytes\" or r._field == \"net_tx_bytes\") and\n       r.pod =~ /${pod:regex}/\n     )\n  // keep RX and TX as separate series per pod\n  |> group(columns: [\"pod\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> derivative(unit: 1s, nonNegative: true)     // bytes/s\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 }))  // bits/s\n  // sum RX+TX together for each pod at each timestamp\n  |> group(columns: [\"pod\", \"_time\"])\n  |> sum()\n  |> group(columns: [\"pod\"])\n  |> yield(name: \"pod_network_total_bps\")"
    }
   ]
  },
  { "title": "Video Streaming App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Video Receiver - Throughput (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) =>\n    r._measurement == \"video_metrics\" and\n    r._field == \"bandwidth_mbps\"\n  )\n  |> map(fn: (r) => ({ \n    r with stream_label: r.stream\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"stream_label\"])\n  |> group(columns: [\"stream_label\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> yield(name: \"video_bandwidth\")\n"
    }
   ]
  },
  {
   "title": "Video Receiver - Frames per Second (FPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"video_metrics\" and\n    r._field == \"fps\"\n  )\n  |> map(fn: (r) => ({\n    r with stream_label: r.stream\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"stream_label\"])\n  |> group(columns: [\"stream_label\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> yield(name: \"video_fps\")\n"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Ping RTT Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"ping\")\n  |> filter(fn: (r) => r._field == \"latency_ms\")\n  |> map(fn: (r) => ({\n      r with\n      combined_label: r.target + \" [\" + r.ip + \"]\"\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"])\n  |> group(columns: [\"combined_label\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> yield(name: \"ping_latency\")\n"
    }
   ]
  },
  {
   "title": "Net I/O Throughput by Interface",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) =>\r\n       r._measurement == \"network_io\" and\r\n       (r._field == \"rx_bytes\" or r._field == \"tx_bytes\") and\r\n       contains(value: r.interface, set: ${interface:json})\r\n     )\r\n  |> group(columns: [\"interface\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n       _time:  r._time,\r\n       _value: r._value * 8.0,\r\n       _field: r.interface + \" \" + (if r._field == \"tx_bytes\" then \"TX\" else \"RX\")\r\n     }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> yield(name: \"net_interface_throughput_bps\")\r\n"
    }
   ]
  },
  {
   "title": "Ping Packet Loss (%)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"ping\")\n  |> filter(fn: (r) => r._field == \"packet_loss_percent\")\n  |> map(fn: (r) => ({\n      r with\n      combined_label: r.target + \" [\" + r.ip + \"]\"\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"])\n  |> group(columns: [\"combined_label\"])\n"
    }
   ]
  }
 ]
}