#version: '3.9'

services:
  mediamtx:
    image: bluenviron/mediamtx:1.11.3
    container_name: mediamtx
    environment:
      - MTX_WEBRTCADDITIONALHOSTS=10.5.1.21 
    ports:
      - "8890:8890/udp" # SRT
      - "8889:8889"     # WebRTC signaling
      - "8189:8189"     # WebRTC media
    restart: always

  receiver-transcoder:
    image: video-receiver-transcoder
    container_name: video-receiver-transcoder
    ports:
      - "5554:5554/udp" # UDP stream for transcoder    
    environment:
      - RECEIVER_PORT=5554
      - WIDTH=1920
      - HEIGHT=1080
      - BITRATE=4000
      - SPEED_PRESET=ultrafast
      - SRT_IP=mediamtx
      - SRT_PORT=8890
      - STREAM_NAME=go1_camera
      - ENABLE_MONITORING=true
      - EXPORT_TO_INFLUXDB=false
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=desire6g2024;
      - INFLUXDB_ORG=desire6g
      - INFLUXDB_BUCKET=infrastructure-monitoring
    volumes:
      - ./receiver-transcoder/app:/app    
    depends_on:
      - mediamtx
    restart: always
