{
 "title": "D6G Site - System Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_percent\")\n  "
      }
     ]
    },
    {
     "title": "RAM Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_usage_percent\")\n"
      }
     ]
    },
    {
     "title": "RAM Total vs Available (GB)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_total_bytes\" or r[\"_field\"] == \"ram_available_bytes\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"]) "
      }
     ]
    }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "RTT Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latency_ms\")\n  |> map(fn: (r) => ({ r with combined_label: r.target_name + \" (\" + r.target_ip + \")\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"]) // Keep only necessary fields\n  |> group(columns: [\"combined_label\"]) // Use the new label\n"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"network_metrics\")\n  |> filter(fn: (r) =>\n      r._field == \"total_pings\" or\n      r._field == \"successful_pings\" or\n      r._field == \"failed_pings\"\n  )\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      IP_Address: r.target_ip,\n      Total: r.total_pings,\n      Success: r.successful_pings,\n      Failed: r.failed_pings\n  }))\n  |> keep(columns: [\"IP_Address\", \"Total\", \"Success\", \"Failed\"])\n"
    }
   ]
  },
  {
   "title": "Packet Loss (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packet_loss_percent\")\n  |> map(fn: (r) => ({ r with combined_label: r.target_name + \" (\" + r.target_ip + \")\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"combined_label\"]) // Keep only necessary fields\n  |> group(columns: [\"combined_label\"]) // Group by target_name + IP\n"
    }
   ]
  },
  { "title": "Video Streaming App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Bandwidth (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => \n    r._measurement == \"video_metrics\" and \n    r._field == \"bandwidth_mbps\"\n  )"
    }
   ]
  },
  {
   "title": "Frames per Second (FPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "frames/sec" } },
   "targets": [
    {
     "query": "from(bucket: \"infrastructure-monitoring\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => \n    r._measurement == \"video_metrics\" and \n    r._field == \"fps\"\n  )"
    }
   ]
  }
 ]
}