version: '3.8'


services:

  go1-base:
    image: go1-base:latest
    container_name: go1-base
    hostname: go1-base
    ports:       
      - "8082:8082/udp"
      - "8090:8090/udp"
      - "8007:8007/udp"
    volumes:
      - ~/unitree-go1-digital-twin/digital-twin-service/go1-base/catkin_ws/src:/home/go1/catkin_ws/src
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=go1-base
      - TARGET_IP=192.168.123.161
      - STATE_LOOP_RATE=100
      - UDP_SEND_DT=0.01
      - UDP_RECEIVE_DT=0.01
      - USE_EKF_ODOM=true
    network_mode: digital-twin-service

  lidar:
    image: rplidar-lidar:latest 
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=lidar
      - RF2O_LASER_ODOMETRY=false
      - ODOM_TOPIC=/lidar_odom
    container_name: lidar
    hostname: lidar
    volumes:
      - "/dev/rplidar:/dev/rplidar"
      - ~/unitree-go1-digital-twin/digital-twin-service/lidar-drivers/catkin_ws/src:/home/lidar/catkin_ws/src

    network_mode: digital-twin-service
    privileged: true

  # phidgets-imu:
  #   image: phidgets-imu:latest 
  #   environment:
  #     - ROS_MASTER_URI=http://ros-master:11311
  #     - ROS_HOSTNAME=phidgets-imu
  #     - FRAME_ID=phidgets_imu_link
  #     - FIXED_FRAME=base
  #   container_name: phidgets-imu
  #   hostname: phidgets-imu
  #   network_mode: digital-twin-service
  #   privileged: true