version: '3.8'

networks:
  digital-twin-service:
    name: digital-twin-service
    driver: overlay
    attachable: true

x-ros-config: &ros-config
  - ROS_MASTER_URI=http://ros-master:11311

services:
  ros-master:
    image: ros-master:latest
    container_name: ros-master
    hostname: ros-master
    environment: *ros-config
    privileged: true
    networks:
      - digital-twin-service

  go1-gesture-control:
    image: go1-gesture-control:latest
    container_name: go1-gesture-control
    hostname: go1-gesture-control
    ports:       
      - "8888:8888/tcp"
    environment:
      ROS_MASTER_URI: "http://ros-master:11311"
      CAMERA_TYPE: "webcam"
      WEB_SERVER: "yes"
      CONTROL_LOOP_RATE: "100"
      CMD_VEL: "go1_controller/cmd_vel"
      STAMPED: "true"
    depends_on:
      - ros-master
    privileged: true
    group_add:
      - video
    networks:
      - digital-twin-service 

  rviz-vnc:
    image: rviz-vnc:latest
    container_name: rviz-vnc
    hostname: rviz-vnc
    ports:
      - "6080:80/tcp"
    environment: *ros-config
    privileged: true
    shm_size: '1g' 
    networks:
      - digital-twin-service 

  go1-navigation:
    image: go1-navigation:latest
    container_name: go1-navigation
    hostname: go1-navigation
    environment: *ros-config
    networks:
      - digital-twin-service 

  digital-twin-app:
    image: isaac-sim:2023.1.0-ubuntu22.04
    container_name: digital-twin-app
    hostname: digital-twin-app
    entrypoint: bash
    command: ./runheadless.native.sh -v
    environment:
      ACCEPT_EULA: "Y"
      PRIVACY_CONSENT: "Y"
      ROS_MASTER_URI: "http://ros-master:11311"  
    volumes:
      - ~/docker/isaac-sim/cache/kit:/isaac-sim/kit/cache:rw
      - ~/docker/isaac-sim/cache/ov:/root/.cache/ov:rw
      - ~/docker/isaac-sim/cache/pip:/root/.cache/pip:rw
      - ~/docker/isaac-sim/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ~/docker/isaac-sim/cache/computecache:/root/.nv/ComputeCache:rw
      - ~/docker/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw
      - ~/docker/isaac-sim/data:/root/.local/share/ov/data:rw
      - ~/docker/isaac-sim/documents:/root/Documents:rw
      - ../../digital-twin-service/digital-replica/my-environments:/isaac-sim/my-environments:rw
    runtime: nvidia
    ports:
      - "47995-48012:47995-48012"
      - "49000-49007:49000-49007"
      - "49100:49100"
      - "8211:8211"
      - "8011:8011"
      - "8111:8111"
      - "8311:8311"
    privileged: true
    networks:
      - digital-twin-service