###########################
### go1-gesture-control ###
###########################

apiVersion: v1
kind: Pod
metadata:
  name: go1-gesture-control-deployment
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "ros-network", "ips": ["172.20.50.12/24"] }
    ]'
  labels:
    app: digital-twin-service
    node: go1-gesture-control
spec:
  containers:
  - name: go1-gesture-control
    image: go1-gesture-control
    imagePullPolicy: IfNotPresent
    env:
    - name: ROS_MASTER_URI
      value: "http://172.20.50.10:11311"
    - name: ROS_IP
      value: "172.20.50.12"
    - name: CAMERA_TYPE
      value: "webcam_ip"
    - name: WEB_SERVER
      value: "yes"
    - name: CONTROL_LOOP_RATE
      value: "100"
    - name: CMD_VEL
      value: "go1_controller/cmd_vel"
    - name: STAMPED
      value: "false"
    ports:
    - containerPort: 5000
    volumeMounts:
      - name: webcam
        mountPath: /dev/video0
    securityContext:
      privileged: true
  volumes:
    - name: webcam
      hostPath:
        path: /dev/video0
  nodeSelector:
    nodetype: edge

---

### LoadBalancer service declaration.
### This is required to expose the ports that enable web access to the go1-gesture-control container
apiVersion: v1
kind: Service
metadata:
  name: go1-gesture-control-frontend
  labels:
    app: digital-twin-service
    node: go1-gesture-control
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 5000
  selector:
    node: go1-gesture-control

---
