version: '3.8'


services:

  go1-base:
    image: go1-base:latest
    container_name: go1-base
    hostname: go1-base
    ports:       
      - "8082:8082/udp"
      - "8090:8090/udp"
      - "8007:8007/udp"
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=go1-base
      - TARGET_IP=192.168.123.161
      - STATE_LOOP_RATE=100
      - UDP_SEND_DT=0.01
      - UDP_RECEIVE_DT=0.01
    network_mode: digital-twin-service

  lidar:
    image: rplidar-lidar:latest 
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=lidar
    container_name: lidar
    hostname: lidar
    devices:
      - "/dev/rplidar:/dev/rplidar"
    network_mode: digital-twin-service
    privileged: true

  phidgets-imu:
    image: phidgets-imu:latest 
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=phidgets-imu
    container_name: phidgets-imu
    hostname: phidgets-imu
    network_mode: digital-twin-service
    privileged: true